<?php

function sigmah_form_alter(&$form, &$form_state, $form_id){	
	if ($form_id == 'search_block_form'){
		$form['search_block_form']['#title']= t('Search');
		$form['submit']['#value'] = 'Ok';
		$form['submit']['#theme'] = 'sigmah_search_submit';
		$form['search_block_form']['#theme'] = 'sigmah_search_input';
		
	}elseif(stripos($form_id, 'simplenews_block_form') !== false){	
		
		unset($form['display_mail']['#title']);
		$form['submit']['#theme'] = 'sigmah_simplenews_submit';
		if($form['submit']['#value'] == 'Save'){
			$form['submit']['#value'] = 'Subscribe';			
		}else{
			$form['display_mail']['#type'] = 'hidden';
		}
		if(!isset($form['mail']['#value'])){
			$form['mail']['#theme']= 'sigmah_simplenews_mail';
		    $form['mail']['#title']= '';
		}		
		$form['action']['#type'] = 'hidden';
		$form['action']['#value'] = 'subscribe';
		$form['#redirect'] = 'home';
		
	}elseif ($form_id == 'user_confirm_delete') {
		unset($form['user_delete_action']['#options']['user_delete_delete']);   
	}elseif($form_id == 'contact_mail_page') {
		$form['#redirect'] = FALSE;
		$form['subject']['#weight'] = 1;
		$form['message']['#weight'] = 2;
		$form['name']['#prefix'] = '<h5>'.t('Would you like to receive a reply?').'</h5>'.
	'<p class="if">'.t('If yes, please enter your email address here').' :</p>';
		$form['name']['#weight'] = 4;
		$form['name']['#title'] = t('Name');
		$form['name']['#field_prefix'] = '<table class="login"><tr><td>'.$form['name']['#title'].'</td><td>';
		$form['name']['#field_suffix'] = '</td></tr>';
		unset($form['name']['#title']);
		$form['mail']['#weight'] = 5;
		$form['mail']['#title'] = t('Your e-mail');
		$form['mail']['#field_prefix'] = '<tr><td>'.$form['mail']['#title'].'</td><td>';
		$form['mail']['#field_suffix'] = '</td></tr></table>';
		unset($form['mail']['#title']);
		$form['mail']['#suffix'] = '<em class="baseline">'.t('(If you don\'t have one, a Sigmah.org account will be automatically set up)').'</em>';
		$form['copy']['#weight'] = 6;
		$form['cid']['#type'] = 'radios';
		unset($form['cid']['#options'][0]);
		unset($form['cid']['#title']);
		$form['cid']['#prefix'] = '<h6>'.t('In order to deal with your request more effectively').'</h6><p>'.t('You can specify which forum you would like your posting to appear in (Don\'t worry, a moderator will put your posting in an appropriate forum if you are not sure)').' : '.'</p>';
		$form['cid']['#weight'] = 7;
		$form['submit']['#weight'] = 8;
		$form['submit']['#prefix'] = '<hr />';
		$form['submit']['#theme']= 'sigmah_contact_submit';	
		$form['#submit']['#ahah']=array(
		  'method' => 'close_window',
		);
		
		//$form['#submit'][] = 'sigmah_contact_submit_handler';		
  }
}

function sigmah_contact_submit_handler(&$form, &$form_state){
	$form_state['redirect'] = contact;
	//window.close()
	kpr($form_state);
}

function sigmah_contact_mail_page_submit($form, $form_state){
	drupal_set_message('Message OK');
	
}
/**
 * Implementation of hook_theme()
 */
function sigmah_theme() {
  return array(
    'sigmah_simplenews_submit' => array(
      'arguments' => array('form' => NULL),
    ),
	'sigmah_simplenews_mail' => array(
      'arguments' => array('form' => NULL),
    ),
	/*'sigmah_contact_form' => array(
	  'template' => 'sigmah-contact-form',
      'arguments' => array('form' => NULL),
    ),*/	
	'sigmah_contact_submit' => array(
      'arguments' => array('form' => NULL),
    ),
	'sigmah_search_submit' => array(
      'arguments' => array('form' => NULL),
    ),
	'sigmah_search_input' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
* $form here is the submit button only
* theme for submit button in contact form
*/
function theme_sigmah_contact_submit($form){	
	return '<input type="submit" name="'.$form['#name'].'" id="send" class="envoyer button" value="'.$form['#value'].'" type="'.$form['#type'].'" />';

}
/**
* $form here is the submit button only
* theme for submit button in simplenews block
*/
function theme_sigmah_simplenews_submit($form){	
	return '<input type="'.$form['#button_type'].'" name="'.$form['#name'].'" id="'.$form['#id'].'" value="'.$form['#value'].'"  class="form-submit sinscrire" />';
}
/**
* $form here is the submit button only
* theme for your email in simplenews block
*/
function theme_sigmah_simplenews_mail($form){
	return '<input type="'.$form['#type'].'" maxlength="'.$form['#maxlength'].'" name="'.$form['#name'].'" id="'.$form['#id'].'" size="'.$form['#size'].'" value="'.t('Your email').'" class="input"
	onfocus="if(this.value==\''.t('Your email').'\')this.value=\'\';" onblur="if(this.value==\'\')this.value=\''.t('Your email').'\';" value="'.t('Your email').'"	/>';
}
/**
* $form here is the submit button only
* theme for submit button in simplenews block
*/
function theme_sigmah_search_submit($form){	
	return '<input type="'.$form['#button_type'].'" name="'.$form['#name'].'" id="'.$form['#id'].'" value="'.$form['#value'].'"  class="form-submit ok" />';
}
/**
* $form here is the submit button only
* theme for submit button in simplenews block
*/
function theme_sigmah_search_input($form){	
	return '<input type="'.$form['#type'].'" maxlength="'.$form['#maxlength'].'" name="'.$form['#name'].'" id="'.$form['#id'].'" size="'.$form['#size'].'" value="'.t('Search').'" class="input_rechercher form-text"
	onfocus="if(this.value==\''.t('Search').'\')this.value=\'\';" onblur="if(this.value==\'\')this.value=\''.t('Search').'\';" 	/>';
}
/*
function sigmah_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
	if($node->type == 'book'){
		if($op='view'){
			$internal_link = array('#weight'=> -99,'#value'=>'<a name="node'.$node->nid.'"></a>',);
			$node->content['internal_link'] = $internal_link;
			$s_link = $node->field_sigmah_link;
			$s_value = $s_link[0]['value'];
			$sigmah_link = array('#weight'=> -100,'#value'=>'<a name="'.$s_value.'"></a>',);
			$node->content['field_sigmah_link'] = $sigmah_link;
			return;
		}
	}
	
}
*/


/**
* cron task to keep the book organization of all translations of the 
* Sigmah Guide French version up to date with original French version structure.
*/
function sigmah_cron() {
  for($depth=2;$depth<=9;$depth++) {
    db_query("
INSERT INTO `drupal_menu_links` (`menu_name`, `plid`, `link_path`, `router_path`, `link_title`, `options`, `module`, `hidden`, `external`, `has_children`, `expanded`, `weight`, `depth`, `customized`, `p1`, `p2`, `p3`, `p4`, `p5`, `p6`, `p7`, `p8`, `p9`, `updated`)
SELECT IF(t_dn.language='en','book-toc-219','book-toc-220') menu_name, t_parent_dml.mlid plid, CONCAT('node/',t_dn.nid) link_path, 'node/%%' router_path,  t_dn.title link_title, 'a:1:{s:5:\"alter\";b:1;}' options, 'book' module, 0 hidden, 0 external, 0 has_children, 0 expanded, 0 weight, dml.depth depth, 0 customized,  t_parent_dml.p1 p1,  t_parent_dml.p2 p2,  t_parent_dml.p3 p3,  t_parent_dml.p4 p4,  t_parent_dml.p5 p5,  t_parent_dml.p6 p6,  t_parent_dml.p7 p7,  t_parent_dml.p8 p8,  t_parent_dml.p9 p9, 0 updated
FROM drupal_menu_links dml
  inner join drupal_node t_dn on (dml.link_path = CONCAT('node/',t_dn.tnid) and t_dn.language!='fr')
  inner join drupal_menu_links parent_dml on (parent_dml.mlid = dml.plid)
  inner join drupal_node t_parent_dn on (parent_dml.link_path = CONCAT('node/',t_parent_dn.tnid) and t_parent_dn.language=t_dn.language)                       
  inner join drupal_menu_links t_parent_dml on (t_parent_dml.link_path = CONCAT('node/',t_parent_dn.nid) and t_parent_dml.module='book')
WHERE dml.menu_name = 'book-toc-32' and dml.depth=%d
and CONCAT('node/',t_dn.nid) NOT IN (SELECT link_path FROM drupal_menu_links WHERE module = 'book')
ORDER BY dml.mlid;
    ", $depth);
    
    db_query("
UPDATE drupal_menu_links dml
SET p%d=mlid
WHERE dml.module='book' and dml.p%d=0 and dml.depth=%d;
    ", $depth, $depth, $depth);     
  }
  
  db_query("
INSERT INTO `drupal_book` (`mlid`, `nid`, `bid`)
SELECT mlid, SUBSTRING(link_path, 6), SUBSTRING(menu_name, 10)
FROM drupal_menu_links
WHERE module='book' and mlid NOT IN (SELECT mlid FROM drupal_book);
    "); 

} 


/**
 * Implementation of hook_menu 
 */

function sigmah_menu($may_cache){
  // This deals with a single issue, and if the exact issue number is not present, it returns a NaN, else it returns the summary of the issue
  $items['issue_tracker/%/%'] = array(
				      'title' => t('Issue Tracker'),					       
				      'page callback' => 'retrieve_issue_info',
				      'page arguments' => array(1,2),
				      'access arguments' => array('access content'), 
				      'access' => TRUE,
				      );
  return $items;
}

/**
 * Helper Function which returns the summary of the particular issue or suggestions for the autocomplete of summary or issue number depending upon the context
 */
function retrieve_issue_info($issueData , $multipleResults){
  // $multipleResults can only be true or false :: Implementing the Check
  if(!($multipleResults=="true" || $multipleResults=="false")){
    return drupal_not_found();
  }

  // Case 1 : $issueData holds the issueNumber, and we extract and return the issue Summary as a JSON
  if($multipleResults=="false") { 
    if(!is_numeric($issueData)){ // Return a 404 Page not found, if it is not a number
      return drupal_not_found();
    }
    // Connect to Mantis Database and execute the Query
    connectToMantisDatabase();
    $queryString = "SELECT summary FROM mantis_bug_table WHERE id='".$issueData."';";
    $query = mysql_query($queryString);
    $numResults = mysql_num_rows($query);
    // The results are returnd as JSON
    // the returned JSON has two fields,'issueNumber' and 'issueSumamry'

    if($numResults>0){
      $jsonResult = array();
      while ($row = mysql_fetch_assoc($query)) {
	$jsonResult['issueNumber']=$issueData;
	$jsonResult['issueSummary']=$row['summary'];
      }
      drupal_json($jsonResult);
    }
    else{
      $jsonResult['issueNumber']="NaN";
      $jsonResult['issueSummary']="NaN";
      drupal_json($jsonResult);
    }
  }

  // Case 2 : $issueData may be the issueNumber or a part of text from any issue Summary, and in both the cases we returns a list of issues numbers and summaries as autoComplete Suggestions
  if($multipleResults=="true"){
    // Connect to the Mantis Database
    connectToMantisDatabase();

    if(is_numeric($issueData)){ // issueData holds the Issue Number
      $queryString = "SELECT id,summary FROM mantis_bug_table WHERE id LIKE'%".$issueData."%' LIMIT 10;";
    }
    else{ // issueData holds  excerpt from some issue summary
      $issueData = mysql_real_escape_string($issueData);
      $queryString = "SELECT id,summary FROM mantis_bug_table WHERE summary LIKE'%".$issueData."%' LIMIT 10;";
    }
 
    $query = mysql_query($queryString);
    $jsonResults = array();
       
    while ($row = mysql_fetch_assoc($query)) {
      $jsonResult = array();
      $jsonResult['issueNumber']=$row['id'];
      $jsonResult['issueSummary']=$row['summary'];
      $jsonResults[]=$jsonResult;
    }
    drupal_json($jsonResults);
  }

  exit();
}

/**
 * Helper Function which Connects to the mantis database 
 */
function connectToMantisDatabase(){
  // Database config details
  $db = array(
	      'server' => '127.0.01',
	      'username' => 'root',
	      'password' => '',
	      'database' => 'mantis'
	      );

  $con = mysql_connect($db['server'],$db['username'],$db['password']);
  if (!$con)
    {
      die('Could not connect: ' . mysql_error());
    }
  mysql_select_db($db['database']) or die(mysql_error());
}

/**
 * Aletring the MyAccounts page to hide the Mailing Lists tabs.
 */


function sigmah_menu_alter(&$items) {

  $items['user/%user/mailman_manager']['type'] = MENU_CALLBACK;
  $items['user/%user/user_mailman_register']['type'] = MENU_CALLBACK;
}
?>