<?php

/**
 * @file
 * Install, update and uninstall functions for the revision all module.
 */

/**
 * Implements hook_install().
 */
function revision_all_install() {
  $defaults['revision-all']  = TRUE;
  $defaults['enable-future'] = TRUE;
  $defaults['prevent-override'] = FALSE;

  variable_set('revision_all', $defaults);
}

/**
 * Implements hook_uninstall().
 */
function revision_all_uninstall() {
  variable_del('revision_all');
}
